[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.1,<2.3",
    "streamlit>=1.31,<1.39",
    "openpyxl>=3.1.5",
]
